FROM formapro/nginx-php-fpm:latest-all-exts

## libs
RUN set -x && \
    apt-get update && \
    apt-get install -y --no-install-recommends wget curl openssl ca-certificates nano netcat parallel supervisor htop

RUN mkdir -p /mqs
WORKDIR /mqs
